pidev_crowd_rise_homepage:
    path:     /hello/{name}
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:index }

pidev_crowd_rise_accueil:
    path:     /accueil
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:accueil }
    
pidev_crowd_rise_projet:
    path:     /projet
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:projet }
    
pidev_crowd_rise_utilisable:
    path:     /utilisable
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:utilisable }

pidev_profil_ajouter:
    path:     /ajoutProfil
    defaults: { _controller: PIDEVCrowdRiseBundle:Profil:ajout}

pidev_profil_afficher:
    path:     /afficheProfil/{id}
    defaults: { _controller: PIDEVCrowdRiseBundle:Profil:affiche}

pidev_profil_ajouter_competence:
    path:     /ajouterCompetence/{id}
    defaults: { _controller: PIDEVCrowdRiseBundle:Competence:ajoutCompetence}

pidev_profil_afficher_competence:
    path:     /afficherCompetence/{id}
    defaults: { _controller: PIDEVCrowdRiseBundle:Competence:affiche}
