pidev_crowd_rise_homepage:
    path:     /hello/{name}
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:index }

pidev_crowd_rise_accueil:
    path:     /accueil
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:accueil }
    
pidev_crowd_rise_projet:
    path:     /projet
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:projet }
    
pidev_crowd_rise_utilisable:
    path:     /utilisable
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:utilisable }
    
pidev_crowd_rise_demandesolution:
    path:     /demandesolution
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:demande }
    
pidev_crowd_rise_ajoutersolution:
    path:     /ajoutersolution
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:ajouter }
   
pidev_crowd_rise_consultersolution:
    path:     /consultersolution
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:consulter }


ajouter_problem:
    path:     /ajouter
    defaults: { _controller: PIDEVCrowdRiseBundle:Problem:ajouter }
consulter:
    path:     /consulter{categorie}
    defaults: { _controller: PIDEVCrowdRiseBundle:Problem:Consulter }
modifier:
    path:    /modifier{id}
    defaults: { _controller: PIDEVCrowdRiseBundle:Problem:Modifier }
supprimer:
    path:    /supprimer{id}
    defaults: { _controller: PIDEVCrowdRiseBundle:Problem:Supprimer }
    
afficher:
    path:    /afficher
    defaults: { _controller: PIDEVCrowdRiseBundle:Problem:Afficher }
    
affichersolutionPB:
    path:    /affichersolutionPB{id}
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:consulterPB }
acceptersolution:
    path:    /acceptersolution{idSolution}
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:accepter }  
refusersolution:
    path:    /refusersolution{idSolution}
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:refuser } 
afficherAccepter:
    path:    /afficherAccepter
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:afficherAccepter }  
afficherRefuser:
    path:    /afficherRefuser
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:afficherRefuser } 




