pidev_crowd_rise_homepage:
    path:     /hello/{name}
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:index }

pidev_crowd_rise_accueil:
    path:     /accueil
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:accueil }
    
pidev_crowd_rise_projet:
    path:     /projet
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:projet }
    
pidev_crowd_rise_utilisable:
    path:     /utilisable
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:utilisable }
    
pidev_crowd_rise_demandesolution:
    path:     /demandesolution
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:demande }
    
pidev_crowd_rise_ajoutersolution:
    path:     /ajoutersolution
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:ajouter }
   
pidev_crowd_rise_consultersolution:
    path:     /consultersolution
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:consulter }

pidev_crowd_rise_modifiersolution:
    path:     /modifiersolution
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:modifier }
    
pidev_crowd_rise_AjouterProjet:
    path:     /AjouterProjet
    defaults: { _controller: PIDEVCrowdRiseBundle:Projet:AjouterProjet }
    
pidev_crowd_rise_ListProjet:
    path:     /ListeProjet
    defaults: { _controller: PIDEVCrowdRiseBundle:Projet:ListProjet }
my_image_route:
    path:     /aff/{id}
    defaults: { _controller: PIDEVCrowdRiseBundle:Projet:photo }
    
pidev_crowd_rise_ModifierProjet:
    path:     /ModifierProjet/{id}
    defaults: { _controller: PIDEVCrowdRiseBundle:Projet:ModifierProjet }
    
pidev_crowd_rise_RechercherProjet:
    path:     /RechercherProjet
    defaults: { _controller: PIDEVCrowdRiseBundle:Projet:RechercherProjet }
   
pidev_crowd_rise_SupprimerProjet:
    path:     /SupprimerProjet/{id}
    defaults: { _controller: PIDEVCrowdRiseBundle:Projet:SupprimerProjet }
    
vote:
    path:     /vote
    defaults: { _controller: PIDEVCrowdRiseBundle:Projet:vote }
