pidev_crowd_rise_homepage:
    path:     /hello/{name}
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:index }

pidev_crowd_rise_accueil:
    path:     /accueil
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:accueil }
    
pidev_crowd_rise_projet:
    path:     /projet
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:projet }
    
pidev_crowd_rise_utilisable:
    path:     /utilisable
    defaults: { _controller: PIDEVCrowdRiseBundle:Default:utilisable }
    
pidev_crowd_rise_ajouterSolution:
    path:     /ajouterSolution/{id}
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:ajouterSolution }
   
pidev_crowd_rise_consultersolution:
    path:     /consultersolution
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:consulterSolution }      
    
pidev_crowd_rise_ajoutDemande:
    path:     /ajoutDemande
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:ajoutDemande }
    
pidev_crowd_rise_deleteSolution:
    path:     /deleteSolution/{id}
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:deleteSolution }
    
pidev_crowd_rise_updateSolution:
    path:     /updateSolution/{id}
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:updateSolution }
    
pidev_crowd_rise_consulterOffreSolution:
    path:     /offreSolution
    defaults: { _controller: PIDEVCrowdRiseBundle:Solution:consulterOffreSubmitter }
    
pidev_crowd_rise_credit:
    path:     /rechargeCredit/{id}
    defaults: { _controller: PIDEVCrowdRiseBundle:Finance:ajoutCredit }