services:
#    pidev_crowd_rise.example:
#        class: PIDEV\CrowdRiseBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
     redirect.after.login:
         class: PIDEV\CrowdRiseBundle\Redirection\AfterLoginRedirection
         arguments: [@router]