services:
#    pidev_crowd_rise.example:
#        class: PIDEV\CrowdRiseBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

     notification_controller:
         class: PIDEV\CrowdRiseBundle\Controller\NotificationController
         
     redirect.after.login:
         class: PIDEV\CrowdRiseBundle\Redirection\AfterLoginRedirection
         arguments: [@router]