services:
  acme.socialBarHelper:
    class : Acme\DemoBundle\Templating\Helper\SocialBarHelper
    tags : 
      - {name : 'templating.helper', alias : 'social-buttons'} 
    arguments : [ @templating ]

  twig.extension.acme_social_bar:
    class: Acme\DemoBundle\Twig\Extensions\AcmeTwigSocialBar
    tags:
        - { name: 'twig.extension' }
    arguments : [ @service_container ]